[build-system]
requires = [
  "flit_core>=3.7.1,<3.8.1",
]
build-backend = "pep517"
backend-path = ["backends"]
[project]
name = "awscli"
description = "Universal Command Line Environment for AWS."
authors = [
  {name = "Amazon Web Services"},
]
license = { file = "LICENSE.txt" }
readme = "README.rst"
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Natural Language :: English",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "colorama>=0.2.5,<0.4.7",
    "docutils>=0.10,<0.20",
    "cryptography>=3.3.2,<38.0.5",
    "ruamel.yaml>=0.15.0,<=0.17.21",
    "prompt-toolkit>=3.0.24,<3.0.29",
    "distro>=1.5.0,<1.6.0",
    "awscrt>=0.12.4,<0.17.0",
    "python-dateutil>=2.1,<3.0.0",
    "jmespath>=0.7.1,<1.1.0",
    "urllib3>=1.25.4,<1.27",
    ]

dynamic = ["version",]

[project.urls]
homepage = "http://aws.amazon.com/cli/"

[tool.awscli.sdist]
include = [
    "backends/**/*.py",
    "bin/*",
    "CHANGELOG.rst",
    "tests/**/*",
    "requirements/**/*.txt",
    "configure",
    "Makefile.in",
    "exe/**/*",
]
# end of cli sdist tool section

# end flit

[tool.black]
line-length = 80
target-version = ['py38', 'py39', 'py310', 'py311']
# 'force-exclude' excludes files or directories in addition to the defaults
force-exclude = '(^/.github/*, ^/.vscode/*, .*\.tf)'
# extend-exclude: keep excluding files from .gitignore in addition to the ones specified
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/\{\{cookiecutter.project_name\}\}/.*
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''
skip-string-normalization = true

[tool.ruff]
builtins = ["_"]
cache-dir = "~/.cache/ruff"
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".idea",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
# In addition to the standard set of exclusions, omit all tests, plus a specific file.
extend-exclude = ["debug"]
# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "ANN", "ARG", "B", "BLE", "C", "COM", "D", "DTZ", "E", "EM", "ERA", "EXE", "F", "FBT", "G", "I", "ICN", "INP", "ISC", "N", "PD", "PGH", "PIE", "PL", "PT", "PTH", "Q", "RET", "RUF", "S", "SIM", "T", "TCH", "TID", "TRY", "UP", "W", "YTT"]
# Group violations by containing file.
format = "pylint"
ignore = [ "ANN002", "ANN003", "ANN101", "D211","D213", "S101", "T20", "EM101", "EM102", "ERA001", "D417", "BLE001", "RET504" ]
# Same as Black.
line-length = 120
per-file-ignores = {}
# By default, always enumerate fixed violations.
show-fixes = true
# By default, always show source code snippets.
show-source = false
# Allow imports relative to the "src" and "test" directories.
src = ["", "", ]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
# "FBT", "TRY",
select = ["A", "ANN", "ARG", "B", "BLE", "C", "COM", "D", "DTZ", "E", "EM", "ERA", "EXE", "F", "G", "I", "ICN", "INP", "ISC", "N", "PD", "PGH", "PIE", "PL", "PT", "PTH", "Q", "RET", "RUF", "S", "SIM", "T", "TCH", "TID", "UP", "W", "YTT"]
unfixable = []
task-tags = ["TODO", "FIXME"]
target-version = "py38"

[tool.ruff.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[tool.ruff.pylint]
max-args = 10

[tool.isort]
profile = "black"
skip_gitignore = true
src_paths = [ "", "",  ]

[tool.flake8]
max-line-length = 120
extend-ignore = "E203"

[tool.pytest.ini_options]
# We set error warning filters in order to enforce that particular
# undesired warnings are not emitted as part of the codebase. If you
# want to override these filters with pytest's default warning filters
# (i.e. print out deprecation warnings instead of erroring out on them),
# you can run pytest with the -Wd flag.
filterwarnings = [
    # Prevents declaring tests that cannot be collected by pytest
    "error::pytest.PytestCollectionWarning",
    
    # Prevents use of functionality that is deprecated or pending deprecation
    "error::DeprecationWarning",
    "error::PendingDeprecationWarning",
    
    # Do not error out on deprecation warnings stemming from our current
    # version of setuptools (57.5.0) in a Python 3.10 environment. When we add
    # support for the latest version of setuptools, we should be able to remove
    # these filters.
    'default:The distutils\.sysconfig module is deprecated:DeprecationWarning',
    
    # Python 3.10.9 introduced a new DeprecationWarning for the implicit
    # creation of event loops. Python plans to remove this warning in the
    # next patch. This filter exception should also be removed once it's
    # confirmed that tests are passing again in the latest Python 3.10.
    # https://github.com/python/cpython/issues/100160
    'default:There is no current event loop:DeprecationWarning',
    
    # pytest-cov is incompatible with pytest-xdist 3.x because pytest-cov
    # uses the config variable for rsyncdir. This filter exception should
    # be able to be removed once both of the following issues are resolved.
    # https://github.com/pytest-dev/pytest-cov/issues/557
    # https://github.com/pytest-dev/pytest-xdist/issues/825
    'default:The --rsyncdir command line argument and rsyncdirs config variable are deprecated.:DeprecationWarning'
]

[tool.coverage.run]
command_line = "-m pytest --doctest-modules"
source = [ ]
parallel = true
branch = true # measure branch coverage in addition to statement coverage

[tool.coverage.report]
fail_under = 5

[tool.coverage.paths]
source = [
    "awscli",
    "**/site-packages/awscli",
]

[tool.poetry_bump2version.options]
list = true
allow_dirty = true
tag = true
commit = true
verbose = 1

[tool.pydocstyle]
convention = "google"
add_select = "D401,D404"

[tool.poe.env]
PYTHONWARNINGS = "ignore::Warning:setuptools.command.install"

[tool.poe.tasks]
pyproject-fmt = { shell = "pyproject-fmt pyproject.toml" }
check-lock = { shell = "poetry lock --check | grep -v 'not consistent'", help = "poetry lock workaround for https://github.com/nat-n/poethepoet/issues/91" }
set-lock = { shell = "poetry lock --no-update", help = "Locks the project dependencies in poetry.lock" }
pc-install = { shell = "pre-commit install; gitlint install-hook", help = "Set up commit-msg and pre-commit hooks" }
pc-autoupdate = { shell = "pre-commit autoupdate", help = "Auto update pre-commit hooks" }
pc-reinstall = { shell = "pre-commit uninstall; gitlint uninstall-hook; pre-commit install; gitlint install-hook", help = "Reset commit-msg and pre-commit hooks" }
hooks = { shell = "git add -A; pre-commit run", help = "Run pre-commit hooks" }
isort = { shell = "[ -z '' ] || { export PYTHONWARNINGS='ignore::Warning:setuptools.command.install'; isort  ; }", help = "isort imports in  and " }
black = { shell = "[ -z '' ] || { black  ; }", help = "black formatting in  and " }
tests = { shell = "[ -z '' ] || { poetry run pytest -s --doctest-modules  ; }", help = "pytest's" }
pros = { shell = "prospector --profile prospector.yaml", help = "Prospector" }
b2v = { cmd = "bump2version patch --new-version '${version}' --allow-dirty --commit", args = [{ name = "version", positional = true, multiple = false }], help = "Prospector" }
gcl = { shell = "cz changelog --incremental || { echo 'With incremental changelog we are ok when there is nothing new to add ...'; true; }; python scripts/normalize_changelog.py", help = "Git Changelog" }
gl = { shell = "gitlint", help = "Gitlint last commit" }
gitown = { shell = "gitown --ownership_threshold=1 --codeowners_filename=CODEOWNERS CODEOWNERS", help = "Githib CODEOWNERS" }
format = { shell = "black --check --diff ." }
add = { shell = "git add -A" }
ibtl = { sequence = ["isort", "black", "tests", "lint"] }
doctests = { shell = "poetry run pytest --doctest-modules --verbose ", help = "doctest's" }
deps = { shell = "poetry install --with local-dev,test,docs", help = "Install project dependencies" }
prepare = { sequence = ["locks", "deps", "formats", "tests", "gcl", "gitown", "docs-make", "add", "hooks"], help = "Do things to prepare for release" }
docs-make = { shell = "make docs || true" }
docs-build = { shell = "[ -z '' ] || { rm -fr  || true; poetry run portray as_html; }" }
docs-serve = { shell = "[ -z '' ] || { rm -fr  || true; poetry run portray in_browser --reload; }" }
pu = { shell = "poetry update", help = "Poetry update" }
pule = { sequence = ["pu", "locks", "exports"], help = "Poetry update and exports" }
exports = { sequence = ["export", "export-dev"], help = "Do things to export" }
formats = { sequence = ["isort", "black"], help = "Run checks" }
locks = { sequence = ["set-lock", "check-lock"], help = "Manage poetry.lock" }
ruff = { shell = "[ -z '' ] || { ruff check  ; }", help = "Ruff linter" }
ruff-noqa = { shell = "[ -z '' ] || { ruff check --select RUF --fix  ; }", help = "Ruff linter fix noqa" }
ruff-watch = { shell = "[ -z '' ] || { poe formats; ruff check --watch  ; }", help = "Ruff linter in watch mode" }
ruff-fix = { shell = "[ -z '' ] || { ruff check --fix-only  ; }", help = "Ruff linter fixes" }
tflint = { shell = "env bash bin/run-tflint.sh", help = "Terraform linter" }
tffmt = { shell = "terraform fmt -list=true -recursive -write=true", help = "Terraform formatting" }
cruft = { shell = "git add -A ; poe cruft-checkout :latest:; git status ", help = "Update cruft to latest" }
cruft-chore = { shell = "git add -A ; git commit -m 'chore: cruft update'; [ ! -f VERSION ] || { cat VERSION; git tag --force $(cat VERSION); }; [ 0 -ne $? ] || { git push; git push --tags --force; }", help = "Commit cruft updates" }
cruft-latest = { shell = "poe cruft-checkout :latest: ", help = "Update cruft to latest" }
cruft-all = { sequence = ["cruft", "cruft-chore"], help = "Update cruft stuff in one go." }

[tool.poe.tasks.lint]
shell = """
[ -z '' ] || {
python -m black --check  ;
python -m isort --check-only  ;
ruff check  ;
}
"""
help = "Do a few lint checks"

[tool.poe.tasks.test-cov]
shell = """
[ -z '' ] || {
coverage run -m pytest --doctest-modules  ;
coverage combine;
coverage lcov -o coverage/lcov.info;
coverage report;
}
"""
help = "Check test coverage"

[tool.poe.tasks.export-dev]
shell = """
export PYTHONWARNINGS=ignore::Warning:setuptools.command.install
python3 -m poetry export --without-hashes --with dev -f requirements.txt -o requirements-dev.txt
"""
help = "Export poetry deps to requirements-dev.txt"
interpreter = "bash"

[tool.poe.tasks.export]
shell = """
export PYTHONWARNINGS=ignore::Warning:setuptools.command.install
python3 -m poetry export --without-hashes -f requirements.txt -o requirements.txt
"""
help = "Export poetry deps to requirements.txt"
env = { "PYTHONWARNINGS" = "ignore::Warning:setuptools.command.install" }
interpreter = "bash"

[tool.poe.tasks.cruft-checkout]
shell = "cruft update --force --strict --override --allow-modified-files --checkout ${checkout}"
help = "Run cruft update"
args = [
    { name = "checkout", positional=true, help = "Tag to check out", required = true, multiple = false },
]

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.26.6"
version_files = [
    ".bumpversion.cfg",
    "VERSION",
    "pyproject.toml:version",
]
tag_format = "v$version"
style = [
    ["qmark", "fg:#ff9d00 bold"],
    ["question", "bold"],
    ["answer", "fg:#ff9d00 bold"],
    ["pointer", "fg:#ff9d00 bold"],
    ["highlighted", "fg:#ff9d00 bold"],
    ["selected", "fg:#cc5454"],
    ["separator", "fg:#cc5454"],
    ["instruction", ""],
    ["text", ""],
    ["disabled", "fg:#858585 italic"]
]

[tool.portray]
docs_dir = "docs"
output_dir = ""
modules = ["awscli"]
port = 8000
append_directory_to_python_path = true
include_reference_documentation = true
extra_markdown_extensions = ["admonition", "codehilite", "extra"]

[tool.portray.pdocs]
# TODO: [2023-01-25 Christo]: excluded_modules = ["cli.console.vendor",]

[tool.portray.mkdocs]
site_name = "Universal Command Line Environment for AWS."
site_description = "Universal Command Line Environment for AWS."
site_url = "https://aws-cli.docs.infra-area2.com/"
repo_url = "https://github.com/SandsB2B/aws-cli"
edit_uri = "edit/master"
copyright = "(c) 2022 Las Vegas Sands"

extra = { generator = false }
extra_css = ["/docs/css/termynal.css", "/docs/css/custom.css"]
extra_javascript = ["/docs/js/termynal.js", "/docs/js/custom.js"]
strict = true
#hooks = [ "docs/hooks/clusters_hook.py" ] [2023-01-26 Christo] Requires 1.4.x

#[tool.portray.mkdocs.plugins]
#"mkdocs-simple-hooks" = { hooks = { "on_config" = "docs.hooks.clusters:on_config" } }

[tool.portray.mkdocs.theme]
name = "material"
features = [ "search.suggest", "search.highlight", "content.tabs.link" ]
icon = { repo = "fontawesome/brands/github" }
custom_dir = "docs/overrides"

[[tool.portray.mkdocs.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "green"
accent = "brown"
toggle = { icon = "material/lightbulb", name = "Switch to light mode" }

[[tool.portray.mkdocs.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "green"
accent = "yellow"
toggle = { icon = "material/lightbulb-outline", name = "Switch to dark mode" }

[tool.cruft]
skip= ["CODEOWNERS","docs/TODO.md","README.md","Makefile",".gitignore","poetry.toml","tests/__init__.py","tests/conftest.py",".python-version",".gitignore",]
